deploy:
  provider: pypi
  user: __token__
  password:
    secure: bramC7FTYNsNBO07yb1K9H/7drrzO75758232P9ObvTOyJE1WewnwF6p3l/tF0YObFnIU1INCMJXSIr9WHXKYPXzGdYMv02Xjhd1tH5huZxVe1tmKWz4KZzAaIBXz7rpvZW4kmgKvIG50XHITn+lwzNuu70HvKzqpN/Y3/ab5+ZJKo0y+kl2FH8B6etkQIIOc0rEw4jF+RbT1i0PIZOLd3/kgsFNrHx8FijbvNBz45g8V5+Eta6aZKCDbxYEMHSqSo7/pWI8NXezVd1Qxd08zUCRaIN5c2TLAfKShPHTci72A5VaPSDUVu9X9hIBiVYyKCC2lSYQSzzmSRY/xv2GmsVzY3I6ozFHppLMQ+WyQv759Pcc0pmn7psEP5BKgCHMT9nQ3X3HI9siTyVvc1QtSGSn2D8GxSDa6oyqtBmKJBUiJmKp6RI1R4GXc5VrHgEhGsmSlCIZtt44WcGPCgrJvDsiGsESjgvmFt8S9i6A02YdUjuW5UaGIUYJW10bRs6fsJfgcEME/8rds19WnlO/9Hb1TjIEFCkCboqj8PVSDZGT5ZDmigVJSSx1c+rVau0Twwnnu0qFJp0+tMns10a6riqu9vhiiEq3T/9/E9OEJhjoayrdmqt6ASN4WWNNLU3KTX/bXfdhOrYcvKEao20maHwkObYQSPF7VnvuOxvtLs4=
  on:
    # TRAVIS_TAG has to match the version.txt and the version has to be major.minor.patch
    condition: $TRAVIS_TAG =~ [0-9]+[.][0-9]+[.][0-9] && $TRAVIS_TAG == `cat version.txt`
    repo: dotslash/recent2
    # Only master
    branch: master
language: python
python:
  - "3.4"