language: python
python:
  - '3.5'
install:
  # Taken from 
  # https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Create a test env with the desired python version
  - conda create -q -n testenv python=$TRAVIS_PYTHON_VERSION
  - conda activate testenv
script: bash scripts/install_test.sh
deploy:
  provider: pypi
  user: __token__
  # Distribute only wheel. No sdist
  distributions: "bdist_wheel" 
  password:
    secure: j2C/JN/4CW6zVX5A30g7XwRiXQ+xShlHsZuAaKfObsJWUNsA6M72XBvfqNRgPtCLVkcSmWPj12gwjsI4FY0u6Y7WLi16LlU80PysUYs6HsdXHXmZ78N46eZpIr3Ikj2XYgWleMaA+dSeGoWdtpMxafu/NBsMlf2ZELMlb45Yo2w9Y8rFF5/0vMHsFjG6kvzsoT7lAwb3U0u2uGrLDdyQSY/MVo6G/mOzra6uEK8F4ed49thJWDQa2/TNKln4CreYCphiy9UtJ7/irqamxHifJGYBuCu7hTrZJ4Ff5rfT0I5NAa4uaTGsFIxM4JN1HTiHcJfKuaLWiCGgs0i53qsxy5IKvZ70qQ+T9yWcGVbD5Qwc3V+di8jEpz4Nqj+HzzuK26vXSa9grxhIq0/ybGK9kOX+xgSHOg7/fl4gcqTTfTExUxPtELDFb112BWuTjpdTvTDnXYRhqcv+9KIXdibWicbazI4FyAu+l5v3OjcWBMxcYBXzHCgtsvmeNC+mcTC3OxkIONmh3oQ56IlexE8OHxuQdn3DY23lvB44K1oRmkthBAUpJ5MX5HQCskBeXFN2uLazuxPzMMtNO7IuKhYFq0M3BpzwrW1Z7Q8zYC7aifyrnjkMQuHUmwCJr5ldkXp9OVCdgF+LMd1QOJkEzIuZYwmRvZkDv7i0xlMIFsj/21k=
  on:
    condition: "$TRAVIS_TAG =~ [0-9]+[.][0-9]+[.][0-9] && $TRAVIS_TAG == `cat version.txt`
      && $TRAVIS_TAG == $TRAVIS_BRANCH"
    repo: dotslash/recent2
    all_branches: true

